### ISSUE TITLE
launchy control

### ISSUE THREAD

**Issue by JestDotty** [JestDotty/web-kingdom#5]
Click shows what's on a tile

Clicking on tile item shows actions that can be done
- long click acts as selector (ie, start area selector, click again to end area selector)

Clicking on action shows list of all available commands
- auto selects first item in list
- last used is sorted to the top (globally sorted)
- input box that filters items with regex
- names of items should be descriptive, ie: workshop: carpenter
- long click/selector indicator

**Comment by Seudein** [comment]
roadmap:

1. selection (done now)
2. input box (done now)
3. actions available
4. action sorting
5. action favoratism
6. mobile inputs?

^ subject to tweaks tho, since usability testing is being 'done'
